### ISSUE TITLE
Remove "game" state

### ISSUE THREAD

**Issue by jahed** [frontiernav/frontiernav#91]
Currently when a game is selected, a bundle is loaded. This bundle contains the game data and the game's graph. However, the app already contains the game data (for listing), so loading it again into a different state isn't correct as desyncing is possible.

There is a difference between the two. The `game` state contains the game guides, description, video url and other data specific to the game overview pages. While the `app` state only contains enough for listing.

This extra data can easily be included in the graph if it's too big to include in the app. But for now I think moving it into the app is good enough.

## To-Do

- [x] Move the extra data from `game` into the `app` state
- [x] Remove `game` state from the root reducer
- [x] Migrate all selectors which use `game` to use `router.params.worldSlug` and `app.data.games`, ideally with a shared selector.
